[package]
name = "w2w2"
version = "0.1.0"
edition = "2021"

[lib]
name = "w2w2"
path = "src/lib.rs"

[dev-dependencies]
assert_matches = "1.5"
rustversion = "1.0"

[dependencies]
wee_alloc = "0.4"
#likely_stable = "0.1.2"
#cached = "0.34.1"
#regex = "1"